exclude = [".git", ".pyenv", ".ruff_cache", ".venv", ".vscode"]
indent-width = 4
target-version = "py312"

[lint]
fixable = ["ALL"]
ignore = ["E501"]
select = ["F", "E", "W", "N", "I", "A", "PLC", "PLE", "PLW"]

[format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"
