services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: validatordb
      POSTGRES_USER: validator
      POSTGRES_PASSWORD: CHANGEME
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "validator", "-d", "validatordb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - validator-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrator:
    image: kinitro-migrator:latest
    build:
      context: ../..
      dockerfile: deploy/docker/migrator.dockerfile
    profiles: ["ops"]
    environment:
      DB_HOST: postgres
      DB_NAME: validatordb
      DB_USER: validator
      DB_PASSWORD: CHANGEME

  validator:
    image: ghcr.io/threetau/kinitro-validator:latest
    build:
      context: ../..
      dockerfile: deploy/docker/validator.dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: validatordb
      DB_USER: validator
      DB_PASSWORD: CHANGEME
    env_file:
      - ${ENV_FILE:-./env/base.env}
    volumes:
      - ./config/base/validator.toml:/etc/kinitro/validator.toml:ro
      - ${BITTENSOR_HOME:-${HOME}/.bittensor}:/var/lib/kinitro/.bittensor

  evaluator:
    profiles: ["cpu"]
    shm_size: "4gb"
    image: ghcr.io/threetau/kinitro-evaluator:latest
    build:
      context: ../..
      dockerfile: deploy/docker/evaluator.dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      validator:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: validatordb
      DB_USER: validator
      DB_PASSWORD: CHANGEME
      RUN_MIGRATIONS: "0"
      KUBECONFIG: /var/lib/kinitro/.kube/config
    env_file:
      - ${ENV_FILE:-./env/base.env}
    volumes:
      - ./config/base/evaluator.toml:/etc/kinitro/evaluator.toml:ro
      - ${HOST_KUBECONFIG:-./config/base/kubeconfig.yaml}:/var/lib/kinitro/.kube/config:ro
      - ${HOST_MINIKUBE_DIR:-./config/base/minikube}:/var/lib/kinitro/.minikube:ro
      - ${BITTENSOR_HOME:-${HOME}/.bittensor}:/var/lib/kinitro/.bittensor
    networks:
      - default
      - minikube

  evaluator-gpu:
    image: ghcr.io/threetau/kinitro-evaluator:latest-gpu
    profiles: ["gpu"]
    build:
      context: ../..
      dockerfile: deploy/docker/evaluator-cuda.dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      validator:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: validatordb
      DB_USER: validator
      DB_PASSWORD: CHANGEME
      RUN_MIGRATIONS: "0"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      MUJOCO_GL: egl
      PYOPENGL_PLATFORM: egl
      KUBECONFIG: /var/lib/kinitro/.kube/config
    env_file:
      - ${ENV_FILE:-./env/base.env}
    volumes:
      - ./config/base/evaluator.toml:/etc/kinitro/evaluator.toml:ro
      - ${HOST_KUBECONFIG:-./config/base/kubeconfig.yaml}:/var/lib/kinitro/.kube/config:ro
      - ${HOST_MINIKUBE_DIR:-./config/base/minikube}:/var/lib/kinitro/.minikube:ro
      - ${BITTENSOR_HOME:-${HOME}/.bittensor}:/var/lib/kinitro/.bittensor
      - /dev/dri:/dev/dri
      - /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - default
      - minikube

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    profiles: ["ops"]
    depends_on:
      validator:
        condition: service_started
    command: ["validator", "evaluator"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "* * * * *"

volumes:
  validator-db:

networks:
  minikube:
    external: true
    name: minikube
