apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
  namespace: kinitro-validator
data:
  validator.toml: |
    [validator]
    backend_url = "wss://api.kinitro.ai/ws/validator"
    pg_database = "postgresql://validator:changeme@validator-postgres.validatordb.svc.cluster.local/validatordb"

apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluator-config
  namespace: kinitro-validator
data:
  evaluator.toml: |
    [evaluator]
    pg_database = "postgresql://validator:changeme@validator-postgres.validatordb.svc.cluster.local/validatordb"
    max_concurrent_jobs = 4
    [evaluator.r2_config]
    endpoint_url = "https://<account-id>.r2.cloudflarestorage.com"
    bucket = "kinitro-artifacts"

---
apiVersion: v1
kind: Secret
metadata:
  name: validator-env
  namespace: kinitro-validator
type: Opaque
stringData:
  .env: |
    KINITRO_API_KEY=replace-me
