apiVersion: v1
kind: Secret
metadata:
  name: validator-db
  namespace: kinitro-validator
type: Opaque
stringData:
  username: validator
  password: changeme
---
apiVersion: v1
kind: Service
metadata:
  name: validator-postgres
  namespace: kinitro-validator
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: validator-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator-postgres
  namespace: kinitro-validator
spec:
  serviceName: validator-postgres
  replicas: 1
  selector:
    matchLabels:
      app: validator-postgres
  template:
    metadata:
      labels:
        app: validator-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: validatordb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: validator-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: validator-db
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
