apiVersion: batch/v1
kind: CronJob
metadata:
  name: validator-rollout
  namespace: kinitro-validator
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: evaluator
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.30
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  set -eux
                  kubectl rollout restart deployment/validator -n kinitro-validator
                  kubectl rollout restart deployment/evaluator -n kinitro-validator || true
                  kubectl rollout restart deployment/evaluator-gpu -n kinitro-validator || true
