[project]
name = "storb-rl"
version = "0.0.1"
description = "Storb RL Subnet"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = [
    "ai2thor>=5.0.0",
    "ray[rllib]>=2.48.0",
]

[dependency-groups]
dev = ["debugpy>=1.8.9", "py-spy>=0.4.0", "pytest>=8.3.4", "ruff>=0.8.2"]
