name: Setup uv
description: Check out repo, install uv, sync dependencies
runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        python-version: "3.12"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: uv sync --extra dev
      shell: bash
