apiVersion: v1
kind: Pod
metadata:
  name: 
spec:
  # runtimeClassName: runc
  restartPolicy: Never
  containers:
  - name: runner
    image: ghcr.io/threetau/kinitro-miner-agent:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: SUBMISSION_URL
        value: 
    command: ["python", "/workspace/submission/main.py", "--host", "0.0.0.0", "--port", "8000"]
    volumeMounts:
      - name: workspace
        mountPath: /workspace/submission
    # Set GPU limits (e.g. nvidia.com/gpu: 1) when the benchmark requires acceleration.
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
  initContainers:
  - name: fetch-submission
    image: ghcr.io/threetau/kinitro-miner-agent:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: SUBMISSION_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['submission-url']
    command:
      - sh
      - -c
      - |
        git clone --depth=1 $SUBMISSION_URL /workspace/submission
        cp /templates/* /workspace/submission/
        if [ -f /workspace/submission/requirements.txt ]; then
          pip install --no-cache-dir -r /workspace/submission/requirements.txt
        fi
    volumeMounts:
      - name: workspace
        mountPath: /workspace/submission
  volumes:
  - name: workspace
    emptyDir: {}
