apiVersion: v1
kind: Pod
metadata:
  name: 
spec:
  # runtimeClassName: runc
  restartPolicy: Never
  containers:
  - name: runner
    image: ghcr.io/threetau/kinitro-miner-agent:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: SUBMISSION_ARCHIVE_URL
        value: ""
      - name: SUBMISSION_ARCHIVE_SHA256
        value: ""
    command: ["python", "/workspace/submission/main.py", "--host", "0.0.0.0", "--port", "8000"]
    volumeMounts:
      - name: workspace
        mountPath: /workspace/submission
    # Set GPU limits (e.g. nvidia.com/gpu: 1) when the benchmark requires acceleration.
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
  initContainers:
  - name: fetch-submission
    image: ghcr.io/threetau/kinitro-miner-agent:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: SUBMISSION_ARCHIVE_URL
        value: ""
      - name: SUBMISSION_ARCHIVE_SHA256
        value: ""
    command:
      - sh
      - -c
      - |
        set -e
        mkdir -p /workspace/submission
        if [ -z "$SUBMISSION_ARCHIVE_URL" ]; then
          echo "SUBMISSION_ARCHIVE_URL is not set" >&2
          exit 1
        fi
        echo "Downloading submission archive from $SUBMISSION_ARCHIVE_URL"
        curl -L --fail "$SUBMISSION_ARCHIVE_URL" -o /tmp/submission.tar.gz
        if [ -n "$SUBMISSION_ARCHIVE_SHA256" ]; then
          echo "$SUBMISSION_ARCHIVE_SHA256  /tmp/submission.tar.gz" | sha256sum -c -
        fi
        tar -xzf /tmp/submission.tar.gz -C /workspace/submission
        cp /templates/* /workspace/submission/
        if [ -f /workspace/submission/requirements.txt ]; then
          pip install --no-cache-dir -r /workspace/submission/requirements.txt
        fi
    volumeMounts:
      - name: workspace
        mountPath: /workspace/submission
  volumes:
  - name: workspace
    emptyDir: {}
