#!/usr/bin/env bash
# Generate worktree-isolated environment configuration
# This script creates .env and docker-compose.override.yml files with unique ports
# based on the current worktree name to avoid collisions between parallel development.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Get worktree name from the directory name
WORKTREE_NAME="$(basename "$REPO_ROOT")"

# Calculate a deterministic port offset based on worktree name hash
# This ensures the same worktree always gets the same ports
get_port_offset() {
    local name="$1"
    # Use first 4 hex chars of md5 hash, convert to decimal, mod 1000
    # This gives us offsets 0-999
    local hash
    hash=$(echo -n "$name" | md5sum | cut -c1-4)
    echo $((16#$hash % 1000))
}

PORT_OFFSET=$(get_port_offset "$WORKTREE_NAME")

# Base ports (default kinitro ports)
BASE_POSTGRES_PORT=5432
BASE_API_PORT=8000
BASE_PROMETHEUS_PORT=9090
BASE_GRAFANA_PORT=3000

# Calculate worktree-specific ports
POSTGRES_PORT=$((BASE_POSTGRES_PORT + PORT_OFFSET))
API_PORT=$((BASE_API_PORT + PORT_OFFSET))
PROMETHEUS_PORT=$((BASE_PROMETHEUS_PORT + PORT_OFFSET))
GRAFANA_PORT=$((BASE_GRAFANA_PORT + PORT_OFFSET))

# Database name based on worktree
DB_NAME="kinitro_${WORKTREE_NAME//-/_}"

echo "Generating environment for worktree: $WORKTREE_NAME"
echo "  Port offset: $PORT_OFFSET"
echo "  PostgreSQL: $POSTGRES_PORT"
echo "  API: $API_PORT"
echo "  Prometheus: $PROMETHEUS_PORT"
echo "  Grafana: $GRAFANA_PORT"
echo "  Database: $DB_NAME"

# Generate .env file
cat > "$REPO_ROOT/.env" << EOF
# Auto-generated by worktree-env.sh for worktree: $WORKTREE_NAME
# Port offset: $PORT_OFFSET

# Database
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_DB=$DB_NAME
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:$POSTGRES_PORT/$DB_NAME

# API
API_PORT=$API_PORT
API_URL=http://localhost:$API_PORT

# Monitoring
PROMETHEUS_PORT=$PROMETHEUS_PORT
GRAFANA_PORT=$GRAFANA_PORT

# Worktree identification
WORKTREE_NAME=$WORKTREE_NAME
EOF

# Generate docker-compose.override.yml (container names only; ports come from .env)
cat > "$REPO_ROOT/docker-compose.override.yml" << EOF
# Auto-generated by worktree-env.sh for worktree: $WORKTREE_NAME
# Container names are unique per worktree; ports are set via .env variables

services:
  postgres:
    container_name: kinitro_postgres_$WORKTREE_NAME

  prometheus:
    container_name: kinitro_prometheus_$WORKTREE_NAME

  grafana:
    container_name: kinitro_grafana_$WORKTREE_NAME
EOF

echo ""
echo "Generated:"
echo "  $REPO_ROOT/.env"
echo "  $REPO_ROOT/docker-compose.override.yml"
echo ""
echo "To start services with these settings:"
echo "  docker compose up -d"
echo "  uv run kinitro api --port $API_PORT --database-url \$DATABASE_URL"
