#!/usr/bin/env bash
# Generate worktree-isolated environment configuration
# This script creates .env and docker-compose.override.yml files with unique ports
# based on the current worktree name to avoid collisions between parallel development.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Get worktree name from the directory name
WORKTREE_NAME="$(basename "$REPO_ROOT")"

# Calculate a deterministic port offset based on worktree name hash
# This ensures the same worktree always gets the same ports
get_port_offset() {
    local name="$1"
    # Use first 4 hex chars of md5 hash, convert to decimal, mod 1000
    # This gives us offsets 0-999
    local hash
    if command -v md5sum &>/dev/null; then
        hash=$(echo -n "$name" | md5sum | cut -c1-4)
    elif command -v md5 &>/dev/null; then
        hash=$(echo -n "$name" | md5 | cut -c1-4)
    else
        echo "Error: Neither md5sum nor md5 found" >&2
        exit 1
    fi
    echo $((16#$hash % 1000))
}

PORT_OFFSET=$(get_port_offset "$WORKTREE_NAME")

# Base ports (default kinitro ports)
BASE_POSTGRES_PORT=5432
BASE_API_PORT=8000
BASE_PROMETHEUS_PORT=9090
BASE_GRAFANA_PORT=3000

# Calculate worktree-specific ports
POSTGRES_PORT=$((BASE_POSTGRES_PORT + PORT_OFFSET))
API_PORT=$((BASE_API_PORT + PORT_OFFSET))
PROMETHEUS_PORT=$((BASE_PROMETHEUS_PORT + PORT_OFFSET))
GRAFANA_PORT=$((BASE_GRAFANA_PORT + PORT_OFFSET))

# Database name based on worktree
DB_NAME="kinitro_${WORKTREE_NAME//-/_}"

echo "Generating environment for worktree: $WORKTREE_NAME"
echo "  Port offset: $PORT_OFFSET"
echo "  PostgreSQL: $POSTGRES_PORT"
echo "  API: $API_PORT"
echo "  Prometheus: $PROMETHEUS_PORT"
echo "  Grafana: $GRAFANA_PORT"
echo "  Database: $DB_NAME"

# Generate .env file from .env.example
ENV_EXAMPLE="$REPO_ROOT/.env.example"
ENV_FILE="$REPO_ROOT/.env"

if [[ ! -f "$ENV_EXAMPLE" ]]; then
    echo "Error: .env.example not found at $ENV_EXAMPLE"
    exit 1
fi

# Copy .env.example as base
cp "$ENV_EXAMPLE" "$ENV_FILE"

# Add worktree header
sed -i '1i # Worktree: '"$WORKTREE_NAME"' (port offset: '"$PORT_OFFSET"')\n# Auto-configured by worktree-env.sh - ports and database are worktree-specific\n' "$ENV_FILE"

# Update POSTGRES_DB to worktree-specific name
sed -i 's/^POSTGRES_DB=.*/POSTGRES_DB='"$DB_NAME"'/' "$ENV_FILE"

# Append worktree-specific port configuration
cat >> "$ENV_FILE" << EOF

# WORKTREE-SPECIFIC CONFIGURATION (auto-generated)
# -----------------------------------------------------------------------------
POSTGRES_PORT=$POSTGRES_PORT
API_PORT=$API_PORT
API_URL=http://localhost:$API_PORT
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:$POSTGRES_PORT/$DB_NAME
PROMETHEUS_PORT=$PROMETHEUS_PORT
GRAFANA_PORT=$GRAFANA_PORT
WORKTREE_NAME=$WORKTREE_NAME
EOF

# Generate docker-compose.override.yml (container names only; ports come from .env)
cat > "$REPO_ROOT/docker-compose.override.yml" << EOF
# Auto-generated by worktree-env.sh for worktree: $WORKTREE_NAME
# Container names are unique per worktree; ports are set via .env variables

services:
  postgres:
    container_name: kinitro_postgres_$WORKTREE_NAME

  prometheus:
    container_name: kinitro_prometheus_$WORKTREE_NAME

  grafana:
    container_name: kinitro_grafana_$WORKTREE_NAME
EOF

echo ""
echo "Generated:"
echo "  $REPO_ROOT/.env"
echo "  $REPO_ROOT/docker-compose.override.yml"
echo ""
echo "To start services with these settings:"
echo "  ./scripts/services.sh start"
echo ""
echo "Or manually:"
echo "  docker compose up -d"
echo "  uv run kinitro api --port $API_PORT --database-url \$DATABASE_URL"
