name: Copy Submission Files on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run copy_submission_files.py
        run: python copy_submission_files.py
